package window.buttons;

public enum TypeButton {

    START_BUTTON,
    OPTIONS_BUTTON,
    START_MENU_BUTTON,
    EXIT_GAME_BUTTON,
    BACK_TO_GAME_BUTTON,
    BACK_BUTTON,
    MOVE_OPTIONS_RADIO_BUTTON,
    TANK_CHOICE_RADIO_BUTTON,
    EXIT_BUTTON,
    START_STAGE_1,
    START_STAGE_2,
    START_STAGE_3,
    START_STAGE_4,
    SIMPLE_HERO_TANK,
    FAST_HERO_TANK,
    POWER_HERO_TANK,
    SUPER_HERO_TANK
}
